name: Check PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**'

env:
  NODE_VERSION: 22
  YARN_VERSION: 1.22.22

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Yarn
        id: install-yarn
        shell: bash
        run: |
          npm install -g yarn@${{ env.YARN_VERSION }}
          yarn set version ${{ env.YARN_VERSION }}

      - name: Install dependencies
        shell: bash
        run: |
          yarn install --frozen-lockfile

      - name: Run lint
        run: yarn lerna run lint

      - name: Run build
        run: yarn lerna run build

      - name: Run tests
        run: yarn lerna run test
